# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-19 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userDetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddress',
            new_name='UserAddres',
        ),
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
